#!/bin/pwsh
Write-host ":| system |" $PSVersionTable.OS
Write-host ":| kernel |" $null$([environment]::OSVersion.Version)
Write-host ":| device |" $([System.Net.Dns]::GetHostName())
Write-host $(tput setab 12) $(tput setab 4) $(tput sgr0) ":| host   | "$(cat /sys/devices/virtual/dmi/id/product_name)
Write-host $(tput setab 13) $(tput setab 5) $(tput sgr0) ":| shell  | "$(basename $SHELL)
Write-host $(tput setab 14) $(tput setab 6) $(tput sgr0) ":| wm     | "$(id=$(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}'); xprop -id "${id}" -notype -f _NET_WM_NAME 8t | grep "_NET_WM_NAME = " | cut --delimiter=' ' --fields=3 | cut --delimiter='"' --fields=2)
Write-host $(tput setab 15) $(tput setab 7) $(tput sgr0) ":| gtk    | "$(grep 'gtk-theme-name' $HOME/.config/gtk-3.0/settings.ini | cut -d' ' -f 3)
Write-host $(tput setab 8) $(tput setab 0) $(tput sgr0) ":| pkgs   | "$(ls -1q /usr/bin | wc -l)
