#!/bin/sh

prin() {
	printf "\033[10%sm \033[4%sm \033[0m :| %-6s | %s\n" "$1" "$1" "$2" "$3"
}

if [ -f /bedrock/etc/bedrock-release ]; then
	read -r distro < /bedrock/etc/bedrock-release
	prin 1 distro "$distro"
elif [ -f /etc/os-release ]; then
	. /etc/os-release
	prin 1 distro "$NAME"
else
	prin 1 os "$(uname -o)"
fi

prin 2 kernel "$(uname -r)"
prin 3 device "$(uname -n) $(uname -m)"

read -r dev < /sys/devices/virtual/dmi/id/product_name
prin 4 host "$dev"
prin 5 shell "${SHELL##*/}"

id=$(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}');
prin 6 wm "$(xprop -id "${id}" -notype -f _NET_WM_NAME 8t | grep "_NET_WM_NAME = " \
	| cut --delimiter=' ' --fields=3 | cut --delimiter='"' --fields=2)"
prin 7 gtk "$(grep gtk-theme-name "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini" | cut -d= -f2 )"
prin 0 bins "$(find /usr/bin | wc -l)"
